const adjectives = [
    "Großer",
    "Kleiner",
    "Schneller",
    "Langsamer",
    "Starker",
    "Schwacher",
    "Schöner",
    "Hässlicher",
    "Freundlicher",
    "Feindlicher",
    "Kluger",
    "Dummer",
    "Mutiger",
    "Schüchterner",
    "Lauter",
    "Leiser",
    "Bunter",
    "Einfarbiger",
    "Wilder",
    "Zahmer",
    "Schnurriger",
    "Flauschiger",
    "Glatter",
    "Rauer",
    "Langer",
    "Kurzer",
    "Roter",
    "Blauer",
    "Grüner",
    "Gelber",
    "Oranger",
    "Lilaner",
    "Rosaner",
    "Brauner",
    "Grauer",
    "Pinker",
    "Türkiser",
    "Violetter",
    "Golder",
    "Silberner",
]

const subjectives = [
    "Hund",
    "Katze",
    "Löwe",
    "Tiger",
    "Elefant",
    "Pferd",
    "Kuh",
    "Schwein",
    "Schaf",
    "Huhn",
    "Ente",
    "Gans",
    "Adler",
    "Falke",
    "Pinguin",
    "Känguru",
    "Panda",
    "Giraffe",
    "Nashorn",
    "Zebra",
    "Fuchs",
    "Wolf",
    "Bär",
    "Affe",
    "Delfin",
    "Wal",
    "Hai",
    "Krokodil",
    "Schlange",
    "Papagei"
]

function choose(values) {
    return values[Math.floor(Math.random() * values.length)]
}

export function name() {
    return `${choose(adjectives)} ${choose(subjectives)}`
}
